### PR TITLE
fix yanking

### PR DESCRIPTION
**Pull request by vale981**

### CODE REVIEW

**Comment by jyp** [comment]
Thanks! No one owns the workman mappings, btw. Let me know if you're interested in developing them.

**Comment by vale981** [comment]
I am :)

**Comment by jyp** [comment]
Then I'll approve any (roughly reasonable) PR you'll make on the workman file.

**Comment by vale981** [comment]
I haven't forgotten my commitment :) and been using my version of boon workman very successfully in the last months.
I still have to integrate some functionality I never use into the keymap and that's where it currently hangs :stuck_out_tongue_closed_eyes:.
Also, some keybindings are not very mnemonic like `s` for `enter insert mode`.

**Comment by jyp** [comment]
The thing with mnemonics is that they do not need to be logical. Example: "enter in "Sert" mode". Very stupid, impossible to forget.

**Pull request merged**
